#!/usr/bin/env bash
# One-command first-run setup for Snaplicator.
#
#   make setup        (or)   ./scripts/setup.sh
#
# Installs dependencies, walks you through configs/.env with sane defaults,
# runs the preflight doctor, and (optionally) brings up the replica + servers.
#
# Testing / automation knobs (not needed for normal use):
#   ENV_FILE=<path>        write env here instead of configs/.env
#   SETUP_SKIP_DEPS=1      skip dependency install
#   SETUP_SKIP_LAUNCH=1    skip the replica/dev launch prompts
#   SETUP_RECONFIGURE=1    overwrite an existing env file without asking
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/.." >/dev/null 2>&1 && pwd)"
cd "$ROOT_DIR"

ENV_FILE="${ENV_FILE:-configs/.env}"

c_b() { printf '\033[1m%s\033[0m\n' "$*"; }
c_g() { printf '\033[32m%s\033[0m\n' "$*"; }
c_y() { printf '\033[33m%s\033[0m\n' "$*"; }
c_c() { printf '\033[36m%s\033[0m\n' "$*"; }

if [ ! -t 0 ] && [ -z "${SETUP_ANSWERS:-}" ]; then
  echo "setup.sh is interactive — run it in a terminal." >&2
  exit 1
fi

c_b "
╔══════════════════════════════════════════╗
║      Snaplicator — first-run setup       ║
╚══════════════════════════════════════════╝"

# ── existing env handling ──────────────────────────────────────────
if [ -f "$ENV_FILE" ] && [ "${SETUP_RECONFIGURE:-0}" != "1" ]; then
  c_y "$ENV_FILE already exists."
  read -r -p "Reconfigure it (a backup is kept)? [y/N] " ans
  case "${ans,,}" in
    y|yes)
      cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
      c_c "Backed up existing env." ;;
    *)
      c_c "Keeping existing $ENV_FILE — skipping to dependency install + doctor."
      SETUP_KEEP_ENV=1 ;;
  esac
fi

# ── prompt helpers ─────────────────────────────────────────────────
declare -A V
ask() {  # ask VAR "Question" "default"
  local var="$1" q="$2" def="${3:-}" in
  if [ -n "$def" ]; then
    read -r -p "$q [$def]: " in || true
    V["$var"]="${in:-$def}"
  else
    read -r -p "$q: " in || true
    V["$var"]="${in:-}"
  fi
}
ask_secret() {  # ask_secret VAR "Question"
  local var="$1" q="$2" in
  read -r -s -p "$q: " in || true
  echo
  V["$var"]="${in:-}"
}

if [ "${SETUP_KEEP_ENV:-0}" != "1" ]; then
  c_b "
1) Replica container"
  ask CONTAINER_NAME  "Container name"        "snaplicator_replica"
  ask NETWORK_NAME    "Docker network name"   "pg_replication_network"
  ask HOST_PORT       "Replica Postgres port" "5432"
  ask POSTGRES_USER   "Replica DB user"       "replica_user"
  ask_secret POSTGRES_PASSWORD "Replica DB password"
  ask POSTGRES_DB     "Replica DB name"       "mydb"
  ask POSTGRES_IMAGE  "Postgres image"        "postgres:17"

  c_b "
2) btrfs storage (snapshots/clones live here)"
  ask ROOT_DATA_DIR   "Root data dir (on btrfs)" "/data/snaplicator"
  ask MAIN_DATA_DIR   "Main replica subvolume"   "replica"

  c_b "
3) Primary (production publisher) connection"
  ask PRIMARY_HOST     "Primary host"     ""
  ask PRIMARY_PORT     "Primary port"     "5432"
  ask PRIMARY_DB       "Primary database" "mydb"
  ask PRIMARY_USER     "Replication role" "replication_user"
  ask_secret PRIMARY_PASSWORD "Replication role password"
  ask PGSSLMODE        "SSL mode (prefer/require/disable)" "prefer"
  ask PUBLICATION_NAME  "Publication name"  "snaplicator_publication"
  ask SUBSCRIPTION_NAME "Subscription name" "snaplicator_subscription"
  ask DUMP_SCHEMAS      "Schemas to schema-clone (csv)" "public"

  c_b "
4) postgres_fdw (optional — live read-only access to non-replicated tables)"
  read -r -p "Enable FDW? [y/N] " fdw_ans
  case "${fdw_ans,,}" in
    y|yes)
      ask FDW_USER "FDW (read-only) role" ""
      ask_secret FDW_PASSWORD "FDW role password"
      ask FDW_HOST "FDW host (blank = same as primary)" ""
      ask FDW_PORT "FDW port (blank = same as primary)" ""
      ask FDW_DB   "FDW database (blank = same as primary)" "" ;;
    *) V[FDW_USER]=""; V[FDW_PASSWORD]="" ;;
  esac

  mkdir -p "$(dirname "$ENV_FILE")"
  {
    echo "# Generated by scripts/setup.sh on $(date -Is)"
    echo
    echo "# ── Replica container ──"
    for k in CONTAINER_NAME NETWORK_NAME HOST_PORT POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_IMAGE; do
      echo "$k=${V[$k]}"
    done
    echo
    echo "# ── btrfs storage ──"
    for k in ROOT_DATA_DIR MAIN_DATA_DIR; do echo "$k=${V[$k]}"; done
    echo
    echo "# ── Primary (publisher) ──"
    for k in PRIMARY_HOST PRIMARY_PORT PRIMARY_DB PRIMARY_USER PRIMARY_PASSWORD PGSSLMODE PUBLICATION_NAME SUBSCRIPTION_NAME DUMP_SCHEMAS; do
      echo "$k=${V[$k]}"
    done
    echo
    echo "# ── FDW (postgres_fdw) ──"
    for k in FDW_USER FDW_PASSWORD; do echo "$k=${V[$k]:-}"; done
    for k in FDW_HOST FDW_PORT FDW_DB; do
      [ -n "${V[$k]:-}" ] && echo "$k=${V[$k]}"
    done
  } > "$ENV_FILE"
  c_g "
✔ Wrote $ENV_FILE"
fi

# ── dependencies ───────────────────────────────────────────────────
if [ "${SETUP_SKIP_DEPS:-0}" != "1" ]; then
  c_b "
5) Installing dependencies (this can take a few minutes)…"
  if [ ! -x backend/.venv/bin/python ]; then
    c_c "  • backend venv + pip install"
    make server-prepare
  else
    c_c "  • backend venv exists — skipping"
  fi
  if [ ! -d frontend/node_modules ]; then
    c_c "  • frontend pnpm install"
    ( cd frontend && pnpm install )
  else
    c_c "  • frontend deps exist — skipping"
  fi
fi

# ── preflight ──────────────────────────────────────────────────────
c_b "
6) Preflight check"
set +e
ENV_FILE="$ENV_FILE" make doctor
DOCTOR_RC=$?
set -e
if [ "$DOCTOR_RC" -ne 0 ]; then
  c_y "
Preflight found blocking issues (see ✘ above). Fix them, then re-run:
  ./scripts/setup.sh        (or)   make doctor"
  exit "$DOCTOR_RC"
fi

# ── launch ─────────────────────────────────────────────────────────
if [ "${SETUP_SKIP_LAUNCH:-0}" = "1" ]; then
  c_g "
✔ Setup complete (launch skipped). Next: make replica && make dev"
  exit 0
fi

c_b "
7) Launch"
read -r -p "Bring up the replica now (make replica)? [Y/n] " r1
case "${r1:-y}" in
  n|N) c_c "Skipped. Run 'make replica' when ready." ;;
  *)   make replica ;;
esac

read -r -p "Start the API + UI now (make dev)? [Y/n] " r2
case "${r2:-y}" in
  n|N) c_c "Skipped. Run 'make dev' when ready." ;;
  *)
    c_g "
Starting… open the UI at:  http://localhost:3000
(API at http://localhost:8888 — docs at /docs)
"
    make dev ;;
esac
